#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
CLAUDE_CONFIG_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
OPENCODE_CONFIG_DIR="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
OPENCLAW_HOME="${OPENCLAW_HOME:-$HOME/.openclaw}"
AGENTS_HOME="${AGENTS_HOME:-$HOME/.agents}"
MARKER="Generated by tui-gamepigeon scripts/install-adapters.sh"

usage() {
  cat <<'EOF'
Usage: scripts/install-adapters.sh [--codex|--claude|--opencode|--hermes|--openclaw|--antigravity|--all]

Install the Tui command for Codex, Claude Code, OpenCode, Hermes, OpenClaw, Antigravity, or all of them (the default).
EOF
}

install_codex=false
install_claude=false
install_opencode=false
install_hermes=false
install_openclaw=false
install_antigravity=false

case "${1:---all}" in
  --all)
    install_codex=true
    install_claude=true
    install_opencode=true
    install_hermes=true
    install_openclaw=true
    install_antigravity=true
    ;;
  --codex)
    install_codex=true
    ;;
  --claude)
    install_claude=true
    ;;
  --opencode)
    install_opencode=true
    ;;
  --hermes)
    install_hermes=true
    ;;
  --openclaw)
    install_openclaw=true
    ;;
  --antigravity)
    install_antigravity=true
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac

if [[ $# -gt 1 ]]; then
  usage >&2
  exit 2
fi

skill_targets=()
if [[ "$install_codex" == true ]]; then
  skill_targets+=("$CODEX_HOME/skills/arcade")
fi
if [[ "$install_claude" == true ]]; then
  skill_targets+=("$CLAUDE_CONFIG_DIR/skills/arcade")
fi
if [[ "$install_hermes" == true ]]; then
  skill_targets+=("$HERMES_HOME/skills/arcade")
fi
if [[ "$install_openclaw" == true ]]; then
  skill_targets+=("$OPENCLAW_HOME/skills/arcade")
fi
if [[ "$install_antigravity" == true ]]; then
  skill_targets+=("$AGENTS_HOME/skills/arcade")
fi

opencode_command="$OPENCODE_CONFIG_DIR/commands/arcade.md"
files_to_check=()
if (( ${#skill_targets[@]} )); then
  for target in "${skill_targets[@]}"; do
    files_to_check+=("$target/SKILL.md")
  done
fi
if [[ "$install_opencode" == true ]]; then
  files_to_check+=("$opencode_command")
fi

if (( ${#files_to_check[@]} )); then
  for generated_file in "${files_to_check[@]}"; do
    if [[ -f "$generated_file" ]] && ! grep -Fq "$MARKER" "$generated_file"; then
      echo "Refusing to replace an existing adapter: $generated_file" >&2
      exit 1
    fi
  done
fi

# The documented install (`npx -y bun x @tui-games/tui@latest install`) runs out
# of a temp checkout: $TMPDIR/bunx-<uid>-<pkg>/... or an _npx cache. Every hook,
# skill, and launcher command below bakes in $ROOT_DIR, so pointing them at that
# directory works right up until the OS reclaims it — macOS prunes /var/folders
# on its own schedule — and then all of Tui fails silently on every prompt with
# no error surface. Copy the checkout somewhere durable first and install from
# there instead.
#
# The `runtime/node_modules/@tui-games/tui` shape is what keeps it runnable:
# `posthog-node` and `@tauri-apps/api` are real runtime imports resolved by
# walking up to the enclosing node_modules, so that whole directory moves and
# the package keeps its position inside it.
# `scripts/plugin-update.ts` recognises this exact path as a copied adapter.
relocate_ephemeral_root() {
  case "$ROOT_DIR" in
    */_npx/*|*/.npm/_npx/*|*/.bun/install/cache/*|*/bunx-*/*) ;;
    *) return 0 ;;
  esac

  local source_modules
  source_modules="$(cd "$ROOT_DIR/../.." 2>/dev/null && pwd)" || return 0
  # Only relocate the layout we actually know how to reassemble.
  [[ "$(basename "$source_modules")" == "node_modules" ]] || return 0

  local runtime="${GAMEPIGEON_HOME:-$HOME/.gamepigeon}/runtime"
  local dest="$runtime/node_modules"
  local staged="$runtime/.node_modules-incoming.$$"

  mkdir -p "$runtime"
  rm -rf "$staged"
  # Move the whole enclosing node_modules, symlinks and all, rather than the
  # package plus a hand-picked list of siblings. Copying entries individually
  # cannot be made correct: preserving links strands them when the tree they
  # point into is left behind, and dereferencing materialises each top-level
  # package while losing the transitive dependencies a package manager parks
  # beside it in a store (bun's .bun/, pnpm's store) — `posthog-node` without
  # `@posthog/core` resolves right up until it is imported. Taking the tree
  # whole keeps every relative link inside it valid, and needs no special case
  # for scopes or for the package itself.
  cp -R "$source_modules" "$staged" || { rm -rf "$staged"; return 0; }
  # Swap late so a concurrent session keeps running the old copy until the new
  # one is complete on disk.
  rm -rf "$dest"
  mv "$staged" "$dest"

  ROOT_DIR="$dest/@tui-games/tui"
  echo "Copied Tui to $ROOT_DIR so it survives temp-directory cleanup"
}

relocate_ephemeral_root

printf -v launcher_command 'node %q %q --enable' "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/overlay.ts"
printf -v codex_launcher_command 'node %q %q --enable --harness codex' "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/overlay.ts"
printf -v hermes_launcher_command 'node %q %q --enable --harness hermes' "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/overlay.ts"
printf -v openclaw_launcher_command 'node %q %q --enable --harness openclaw' "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/overlay.ts"
printf -v opencode_launcher_command 'node %q %q --enable --harness opencode' "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/overlay.ts"
printf -v antigravity_launcher_command 'node %q %q --enable --harness antigravity' "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/overlay.ts"

if (( ${#skill_targets[@]} )); then
  for target in "${skill_targets[@]}"; do
    mkdir -p "$target"
    harness=""
    update_flag=""
    adapter_launcher_command="$launcher_command"
    if [[ "$target" == "$CODEX_HOME/skills/arcade" ]]; then
      harness="codex"
      adapter_launcher_command="$codex_launcher_command"
    elif [[ "$target" == "$HERMES_HOME/skills/arcade" ]]; then
      harness="hermes"
      adapter_launcher_command="$hermes_launcher_command"
    elif [[ "$target" == "$OPENCLAW_HOME/skills/arcade" ]]; then
      harness="openclaw"
      adapter_launcher_command="$openclaw_launcher_command"
    elif [[ "$target" == "$AGENTS_HOME/skills/arcade" ]]; then
      harness="antigravity"
      adapter_launcher_command="$antigravity_launcher_command"
    fi
    if [[ -n "$harness" ]]; then
      update_flag="--$harness"
      cat > "$target/SKILL.md" <<EOF
---
name: arcade
description: Open or restore the native Tui HTML overlay while the coding harness works.
---

# Tui

<!-- $MARKER -->

Execute this command exactly once:

\`$adapter_launcher_command\`

Do not inspect the user's repository. Do not spawn another agent or task. Do not run any other command.

Tui opens as a borderless HTML overlay without a Dock or taskbar entry. Running Tui again focuses the existing overlay.

On success, respond with \`Tui opened.\`, plus any additional line the command printed (e.g. an \`Update available:\` line) verbatim on the next line, followed by "Run \`npx -y bun x @tui-games/tui@latest install $update_flag\` to update." if such a line was printed. On failure, relay the launcher's error without attempting another launch method.
EOF
    else
      cat > "$target/SKILL.md" <<EOF
---
name: arcade
description: Open or restore the native Tui HTML overlay while the coding harness works.
---

# Tui

<!-- $MARKER -->

Execute this command exactly once:

\`$launcher_command\`

Do not inspect the user's repository. Do not spawn another agent or task. Do not run any other command.

Tui opens as a borderless HTML overlay without a Dock or taskbar entry. Running Tui again focuses the existing overlay.

On success, respond only with \`Tui opened.\`. On failure, relay the launcher's error without attempting another launch method.
EOF
    fi
    echo "Installed Tui skill at $target"
  done
fi

if [[ "$install_opencode" == true ]]; then
  mkdir -p "$(dirname "$opencode_command")"
  cat > "$opencode_command" <<EOF
---
description: Open or restore the Tui overlay
---

<!-- $MARKER -->

!\`$opencode_launcher_command\`

The command opens Tui as a borderless HTML overlay without a Dock or taskbar entry. Running \`/arcade\` again focuses the existing overlay.

Respond with \`Tui opened.\` when the launcher succeeds, plus any \`Update available:\` line verbatim, followed by "Run \`npx -y bun x @tui-games/tui@latest install --opencode\` to update." if such a line was printed. If its output reports an error, relay that error without attempting another launch method.
EOF
  echo "Installed Tui command at $opencode_command"
fi

# A copied skill carries no lifecycle hooks, so on its own the overlay would
# only ever appear when the user explicitly asks for it — never showing while
# the agent works, never pausing when a turn ends. Merge the hooks into each
# harness's user-global config so one install command is the whole setup.
install_harness_hooks() {
  node "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/manage-harness-hooks.ts" "$1" "$ROOT_DIR" "$2"
}

if [[ "$install_claude" == true ]]; then
  install_harness_hooks claude "$CLAUDE_CONFIG_DIR"
fi

if [[ "$install_codex" == true ]]; then
  install_harness_hooks codex "$CODEX_HOME"
fi

if [[ "$install_antigravity" == true ]]; then
  install_harness_hooks antigravity "$AGENTS_HOME"
fi

if [[ "$install_hermes" == true ]]; then
  if [[ -f "$HERMES_HOME/config.yaml" ]]; then
    if [[ -f "$HERMES_HOME/hermes-agent/venv/bin/python" ]]; then
      "$HERMES_HOME/hermes-agent/venv/bin/python" "$ROOT_DIR/scripts/manage-hermes-hooks.py" "$ROOT_DIR"
    else
      python3 "$ROOT_DIR/scripts/manage-hermes-hooks.py" "$ROOT_DIR" || python "$ROOT_DIR/scripts/manage-hermes-hooks.py" "$ROOT_DIR"
    fi
  fi
fi

if [[ "$install_openclaw" == true ]]; then
  mkdir -p "$OPENCLAW_HOME/hooks/arcade"
  cat > "$OPENCLAW_HOME/hooks/arcade/HOOK.md" <<EOF
---
name: arcade
description: "Open or restore the Tui overlay"
metadata:
  {
    "openclaw":
      {
        "emoji": "🎮",
        "events": ["command:new", "command:reset"],
        "install": [{ "id": "arcade", "kind": "local", "label": "Local Tui" }],
      },
  }
---
# Tui Hook
This hook manages the Tui overlay lifecycle.
EOF

  cat > "$OPENCLAW_HOME/hooks/arcade/handler.js" <<EOF
import { exec } from "node:child_process";

export default async function handle(event) {
  const root = "$ROOT_DIR";
  let action = "";
  if (event.action === "new" || event.action === "reset") {
    action = "--reset && node " + root + "/scripts/run-with-bun.cjs " + root + "/scripts/overlay.ts --show";
  }
  if (action) {
    exec("node " + root + "/scripts/run-with-bun.cjs " + root + "/scripts/overlay.ts " + action);
  }
}
EOF

  if command -v openclaw &> /dev/null; then
    openclaw hooks enable arcade || true
  fi
  echo "Installed and enabled OpenClaw hook at $OPENCLAW_HOME/hooks/arcade"
fi
