#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_DIR="${1:-${GAMEPIGEON_WORKSPACE_DIR:-$ROOT_DIR}}"
PLUGIN_DIR="$WORKSPACE_DIR/.agents/plugins/tui-gamepigeon"
MARKER="Generated by tui-gamepigeon scripts/materialize-agents-plugin.sh"

printf -v hook_cmd 'node %q %q' "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/antigravity-hook.ts"
printf -v launcher_command 'node %q %q --enable --harness antigravity' "$ROOT_DIR/scripts/run-with-bun.cjs" "$ROOT_DIR/scripts/overlay.ts"

mkdir -p "$PLUGIN_DIR"
rm -rf "$PLUGIN_DIR/plugin.json" "$PLUGIN_DIR/hooks.json" "$PLUGIN_DIR/skills"
mkdir -p "$PLUGIN_DIR/skills/arcade"
install -m 644 "$ROOT_DIR/.codex-plugin/plugin.json" "$PLUGIN_DIR/plugin.json"

mkdir -p "$WORKSPACE_DIR/.agents/plugins"
cat > "$WORKSPACE_DIR/.agents/plugins/marketplace.json" <<EOF
{
  "name": "tui-gamepigeon-dev",
  "interface": {
    "displayName": "Tui (local checkout)"
  },
  "plugins": [
    {
      "name": "tui-gamepigeon",
      "source": {
        "source": "local",
        "path": "./.agents/plugins/tui-gamepigeon"
      },
      "policy": {
        "installation": "AVAILABLE"
      },
      "category": "Developer Tools"
    }
  ]
}
EOF

cat > "$PLUGIN_DIR/skills/arcade/SKILL.md" <<EOF
---
name: arcade
description: Open or restore the native Tui HTML overlay while the coding harness works.
---

# Tui

<!-- $MARKER -->

Execute this command exactly once:

\`$launcher_command\`

Do not inspect the user's repository. Do not spawn another agent or task. Do not run any other command.

Tui opens as a borderless HTML overlay without a Dock or taskbar entry. Running Tui again focuses the existing overlay.

On success, respond with \`Tui opened.\`, plus any additional line the command printed (e.g. an \`Update available:\` line) verbatim on the next line, followed by "Run \`npx -y bun x @tui-games/tui@latest install --antigravity\` to update." if such a line was printed. On failure, relay the launcher's error without attempting another launch method.
EOF

# Antigravity has no UserPromptSubmit and no SessionEnd, and it drops unknown
# event keys without a word: what it fires is PreToolUse, PostToolUse,
# PreInvocation, PostInvocation, Stop, and SessionStart. scripts/antigravity-hook.ts
# maps the whole overlay lifecycle onto the events that do exist.
cat > "$PLUGIN_DIR/hooks.json" <<EOF
{
  "tui-gamepigeon": {
    "enabled": true,
    "SessionStart": [
      {
        "type": "command",
        "command": "$hook_cmd --session-start"
      }
    ],
    "PreInvocation": [
      {
        "type": "command",
        "command": "$hook_cmd --pre-invocation"
      }
    ],
    "Stop": [
      {
        "type": "command",
        "command": "$hook_cmd --stop"
      }
    ]
  }
}
EOF

echo "Materialized Antigravity workspace plugin at $PLUGIN_DIR"
