#!/usr/bin/env bash
set -euo pipefail

# Install the post-commit and post-merge hooks that keep the installed Tui
# adapters in sync with this checkout. Idempotent, and refuses to clobber a
# hook this script did not write.
#
#   bash scripts/install-git-hooks.sh            # install
#   bash scripts/install-git-hooks.sh --uninstall # remove ours, leave others

MARKER="Generated by tui-gamepigeon scripts/install-git-hooks.sh"
HOOKS=(post-commit post-merge)

uninstall=false
case "${1:-}" in
  "") ;;
  --uninstall) uninstall=true ;;
  -h|--help)
    sed -n '4,10p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  *)
    echo "usage: install-git-hooks.sh [--uninstall]" >&2
    exit 2
    ;;
esac

if [[ $# -gt 1 ]]; then
  echo "usage: install-git-hooks.sh [--uninstall]" >&2
  exit 2
fi

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  echo "install-git-hooks: not inside a git checkout" >&2
  exit 1
fi

# --git-common-dir names the main checkout's .git even from a linked worktree.
# --path-format needs git 2.31, so older git gets the relative answer resolved
# against the top level instead.
resolve_common_dir() {
  local common_dir
  if ! common_dir="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)"; then
    common_dir="$(git rev-parse --git-common-dir)"
    case "$common_dir" in
      /*) ;;
      *) common_dir="$(git rev-parse --show-toplevel)/$common_dir" ;;
    esac
  fi
  (cd "$common_dir" && pwd)
}

COMMON_DIR="$(resolve_common_dir)"
ROOT_DIR="$(cd "$COMMON_DIR/.." && pwd)"
SYNC_SCRIPT="$ROOT_DIR/scripts/sync-arcade-adapters.sh"

# core.hooksPath wins over $GIT_COMMON_DIR/hooks when it is set, so honour it
# rather than writing files git will never run.
if hooks_path="$(git config --get core.hooksPath)" && [[ -n "$hooks_path" ]]; then
  case "$hooks_path" in
    /*) HOOK_DIR="$hooks_path" ;;
    *)
      # A relative core.hooksPath is resolved by git against the working tree
      # root of whichever worktree the hook runs in (githooks(5): git chdirs to
      # the working tree root before invoking a hook), not against one shared
      # directory. So this install covers exactly the worktree it ran in, and
      # commits in sibling worktrees will not find it. Say so rather than
      # reporting a repository-wide install that did not happen.
      top_level="$(git rev-parse --show-toplevel)"
      HOOK_DIR="$top_level/$hooks_path"
      echo "warning: core.hooksPath is relative ($hooks_path)." >&2
      echo "warning: git resolves it per worktree, so this installs only for $top_level." >&2
      echo "warning: re-run inside each linked worktree, or set an absolute core.hooksPath." >&2
      ;;
  esac
else
  HOOK_DIR="$COMMON_DIR/hooks"
fi

mkdir -p "$HOOK_DIR"

if [[ "$uninstall" == true ]]; then
  for hook in "${HOOKS[@]}"; do
    target="$HOOK_DIR/$hook"
    if [[ -f "$target" ]] && grep -Fq "$MARKER" "$target"; then
      rm "$target"
      echo "removed $target"
    fi
  done
  exit 0
fi

for hook in "${HOOKS[@]}"; do
  target="$HOOK_DIR/$hook"
  if [[ -f "$target" ]] && ! grep -Fq "$MARKER" "$target"; then
    echo "Refusing to replace an existing hook: $target" >&2
    exit 1
  fi
done

for hook in "${HOOKS[@]}"; do
  target="$HOOK_DIR/$hook"
  cat > "$target" <<EOF
#!/usr/bin/env bash
# $MARKER
#
# Keep the installed Tui adapters pointed at the main checkout. The sync script
# resolves that checkout itself, so this hook stays correct no matter which
# worktree the commit happened in.
#
# The path is baked at install time. The fallback only runs if the repository
# moved since, and deliberately avoids a bare ".git": in a linked worktree .git
# is a file, so ".git/.." is not a directory and the -f test below would fail,
# silently skipping the sync on git older than 2.31.

sync="$SYNC_SCRIPT"

if [ ! -f "\$sync" ]; then
  common_dir="\$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" ||
    common_dir="\$(git rev-parse --git-common-dir 2>/dev/null)" || exit 0
  case "\$common_dir" in
    /*) ;;
    *) common_dir="\$(git rev-parse --show-toplevel)/\$common_dir" ;;
  esac
  sync="\$common_dir/../scripts/sync-arcade-adapters.sh"
fi

[ -f "\$sync" ] || exit 0
bash "\$sync" --all >/dev/null 2>&1 ||
  echo "tui: adapter sync failed. Run: bash \$sync --all" >&2

# A sync failure must never look like a failed commit or merge.
exit 0
EOF
  chmod +x "$target"
  echo "installed $target"
done
